import type { Config } from 'tailwindcss'
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                   '#3a5f94',
        'primary-dim':               '#2d5387',
        'primary-container':         '#d5e3ff',
        'on-primary':                '#f6f7ff',
        'on-primary-container':      '#2c5287',
        'on-primary-fixed':          '#153f73',
        'secondary':                 '#49636f',
        'secondary-container':       '#cbe7f5',
        'on-secondary-fixed':        '#29434e',
        'secondary-dim':             '#3d5762',
        'tertiary':                  '#5d5d78',
        'tertiary-container':        '#dbdafb',
        'on-tertiary-fixed':         '#393953',
        'tertiary-dim':              '#51516c',
        'surface':                   '#f8f9fb',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f0f4f7',
        'surface-container':         '#e8eff3',
        'surface-container-high':    '#e1e9ee',
        'surface-container-highest': '#d9e4ea',
        'background':                '#f8f9fb',
        'on-background':             '#2a3439',
        'on-surface':                '#2a3439',
        'on-surface-variant':        '#566166',
        'outline':                   '#717c82',
        'outline-variant':           '#a9b4b9',
        'error':                     '#9f403d',
        'error-container':           '#fe8983',
        'on-error-container':        '#752121',
        'inverse-surface':           '#0b0f10',
      },
      fontFamily: {
        headline: ['Public Sans', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
} satisfies Config
