import type { Config } from 'tailwindcss'
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                   '#256386',
        'primary-dim':               '#1d4e6b',
        'primary-container':         '#c5e0ea',
        'on-primary':                '#ffffff',
        'on-primary-container':      '#1b3a5c',
        'on-primary-fixed':          '#0f2a42',
        'secondary':                 '#3a70a9',
        'secondary-container':       '#dbeafe',
        'on-secondary-fixed':        '#1e3a5f',
        'secondary-dim':             '#2d5987',
        'tertiary':                  '#6d8eb0',
        'tertiary-container':        '#e0e7ef',
        'on-tertiary-fixed':         '#3a4f6a',
        'tertiary-dim':              '#5a7a9e',
        'surface':                   '#f0f7f8',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f0f7f8',
        'surface-container':         '#e2eff5',
        'surface-container-high':    '#d4e6ef',
        'surface-container-highest': '#c5dde9',
        'background':                '#f0f7f8',
        'on-background':             '#1b3a5c',
        'on-surface':                '#1b3a5c',
        'on-surface-variant':        '#4f6080',
        'outline':                   '#6d8eb0',
        'outline-variant':           '#bcc0c9',
        'error':                     '#cd5055',
        'error-container':           '#fee2e2',
        'on-error-container':        '#7f1d1d',
        'inverse-surface':           '#1b3a5c',
        'header':                    '#242D4F',
      },
      fontFamily: {
        headline: ['Public Sans', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
} satisfies Config
